import assert from 'node:assert/strict'
import { chromium } from 'playwright-core'
import { homedir } from 'node:os'
import { readdirSync } from 'node:fs'
const cache = `${homedir()}/Library/Caches/ms-playwright`
const shell = readdirSync(cache).filter((d) => d.startsWith('chromium_headless_shell-')).sort().pop()
const browser = await chromium.launch({ executablePath: `${cache}/${shell}/chrome-headless-shell-mac-arm64/chrome-headless-shell` })
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
  page.setDefaultTimeout(10000)
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  let response
  await page.route('https://exercise-ai.test/**', (route) => route.fulfill({ contentType: 'application/json', body: JSON.stringify(route.request().url().endsWith('/models') ? { data: [] } : { choices: [{ message: { content: JSON.stringify(response) } }] }) }))
  await page.goto(process.env.BASE_URL ?? 'http://127.0.0.1:5199/')
  await page.locator('.tabbar .scan-key').waitFor()
  await page.evaluate(async () => { const { api } = await import('/src/data/index.ts'); await api.saveSettings({ ...await api.getSettings(), aiEndpoint: '', aiApiKey: '' }) })
  await page.reload()
  const scan = () => page.locator('.tabbar .scan-key').click()
  const countExercises = () => page.evaluate(async () => (await (await import('/src/data/index.ts')).api.listExercises()).length)
  const workout = () => page.evaluate(async () => (await (await import('/src/data/index.ts')).api.getActiveWorkout()))
  const manual = async () => { await scan(); await page.getByRole('button', { name: 'Pick or add it myself' }).click() }
  const confirm = () => page.getByRole('button', { name: 'Confirm & continue' }).click()
  const finish = () => page.getByRole('button', { name: 'Finish workout' }).click()

  await manual()
  await page.getByRole('group', { name: 'Filter by activity type' }).getByRole('button', { name: 'Cardio', exact: true }).click()
  await page.getByRole('button', { name: /^Elliptical Trainer/ }).click()
  assert.equal(await workout(), undefined, 'review must not start a workout')
  await confirm()
  await page.getByRole('heading', { name: 'Elliptical Trainer' }).waitFor()
  assert.equal(await page.locator('.set-row').count(), 0, 'cardio has no weight/rep rows')
  await page.getByLabel('Minutes', { exact: true }).fill('20')
  await page.getByLabel('Distance · miles (optional)').fill('1.2')
  await page.getByLabel('Resistance level (optional)').fill('5')
  await page.getByRole('button', { name: 'Log activity ✓', exact: true }).click()
  await page.getByText('20 min · 1.2 mi · resistance 5', { exact: false }).waitFor()
  await finish()
  await page.getByText('Timed activity · 20 min', { exact: true }).waitFor()
  console.log('PASS manual/offline catalog → cardio logger → saved summary')

  await page.evaluate(async () => { const { api } = await import('/src/data/index.ts'); await api.saveSettings({ ...await api.getSettings(), aiEndpoint: 'https://exercise-ai.test', aiApiKey: '', aiModel: 'test' }) })
  await page.reload()
  response = { identified: true, name: 'Air Runner', confidence: 'high', explanation: 'A curved belt running machine.', exerciseIds: [], categories: ['cardio'], primaryCategory: 'cardio', muscleGroups: ['quads', 'glutes', 'calves'], primaryMuscles: ['quads', 'glutes'], supportingMuscles: ['calves'], equipment: 'machine', recordingFormat: 'duration-distance', matchKind: 'none' }
  await scan()
  await page.getByRole('button', { name: 'Describe it', exact: true }).click()
  await page.getByLabel('Describe the exercise or workout movement').fill('Running on a curved belt machine')
  await page.getByRole('button', { name: 'Find possible exercises' }).click()
  await page.getByRole('button', { name: /Save “Air Runner” as your own/ }).waitFor()
  const before = await countExercises()
  await page.getByRole('button', { name: /Save “Air Runner” as your own/ }).click()
  assert.equal(await countExercises(), before, 'AI draft is not saved')
  const primary = page.getByRole('group', { name: 'Main muscles — optional' })
  assert.equal(await primary.getByRole('button', { name: 'quads', exact: true }).getAttribute('aria-pressed'), 'true')
  assert.equal(await primary.getByRole('button', { name: 'glutes', exact: true }).getAttribute('aria-pressed'), 'true')
  await page.screenshot({ path: '/tmp/gym-exercise-review.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'mobile has no horizontal overflow')
  await confirm()
  await page.getByRole('heading', { name: 'Air Runner' }).waitFor()
  assert.equal(await countExercises(), before + 1)
  await page.getByLabel('Minutes', { exact: true }).fill('5')
  await page.getByRole('button', { name: 'Log activity ✓', exact: true }).click()
  await page.getByText('1. 5 min', { exact: true }).waitFor()
  await finish()
  console.log('PASS AI no-match → editable category and multi-primary suggestion → custom exercise')

  response = { identified: true, name: 'Dual leg station', confidence: 'high', explanation: 'Choose the movement you performed.', exerciseIds: ['ex-leg-extension', 'ex-leg-curl'], categories: ['strength'], matchKind: 'possible', matchReasons: { 'ex-leg-extension': 'Extend knees', 'ex-leg-curl': 'Bend knees' } }
  await scan()
  await page.getByRole('button', { name: 'Describe it', exact: true }).click()
  await page.getByLabel('Describe the exercise or workout movement').fill('A dual leg machine')
  await page.getByRole('button', { name: 'Find possible exercises' }).click()
  await page.getByText('Which one are you doing?', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Confirm & continue' }).count(), 0)
  await page.getByRole('button', { name: 'Browse similar strength', exact: true }).click()
  await page.getByLabel('Search your exercises').fill('leg press')
  await page.getByRole('button', { name: /^Leg Press/ }).click()
  await page.getByRole('button', { name: 'Assign main and supporting' }).click()
  for (const muscle of ['quads', 'glutes']) await page.getByRole('group', { name: 'Main muscles — optional' }).getByRole('button', { name: muscle, exact: true }).click()
  await confirm()
  await page.getByRole('heading', { name: 'Leg Press' }).waitFor()
  const roleCheck = await page.evaluate(async () => (await (await import('/src/data/index.ts')).api.getExercise('ex-leg-press')).primaryMuscles)
  assert.deepEqual(roleCheck, ['quads', 'glutes'])
  await page.locator('.set-row').first().getByLabel('Weight in pounds').fill('100')
  await page.locator('.set-row').first().getByLabel('Set 1 reps', { exact: true }).fill('10')
  await page.locator('.set-row').first().locator('.set-done-btn').click()
  await page.locator('.set-done-btn.done').waitFor()
  await finish()
  console.log('PASS ambiguous machine requires choice; edited leg press logs normal strength sets')

  await manual()
  await page.getByRole('button', { name: 'Add one manually' }).click()
  await page.getByLabel('Exercise name').fill('Air Runner')
  await page.getByRole('button', { name: 'Use existing exercise' }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Confirm & continue' }).isDisabled(), true)
  await page.getByRole('button', { name: 'Use existing exercise' }).click()
  await confirm()
  await page.getByRole('heading', { name: 'Air Runner' }).waitFor()
  await page.getByText('Last time: 5 min', { exact: true }).waitFor()
  console.log('PASS duplicate prevention and prior timed performance')
  await page.getByLabel('Minutes', { exact: true }).fill('1')
  await page.getByRole('button', { name: 'Log activity ✓', exact: true }).click()
  await page.getByText('1. 1 min', { exact: true }).waitFor()
  await finish()

  await page.locator('.tabbar').getByRole('button', { name: 'Train', exact: true }).click()
  await page.getByRole('button', { name: 'New routine' }).click()
  await page.locator('input[placeholder="Push day"]').fill('Cardio targets')
  await page.locator('select').selectOption('ex-elliptical')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.getByLabel('Target minutes (optional)').fill('12')
  await page.getByLabel('Target miles (optional)').fill('2')
  await page.getByRole('button', { name: 'Save routine' }).click()
  await page.getByText('Cardio targets', { exact: true }).click()
  await page.getByRole('heading', { name: 'Elliptical Trainer' }).waitFor()
  assert.equal(await page.getByLabel('Minutes', { exact: true }).inputValue(), '12')
  assert.equal(await page.getByLabel('Distance · miles (optional)').inputValue(), '2')
  await page.getByRole('button', { name: 'Log activity ✓', exact: true }).click()
  await page.getByText('1. 12 min · 2 mi', { exact: true }).waitFor()
  await finish()
  console.log('PASS cardio routine stores time/distance targets and prefills the logger')

  await manual()
  await page.getByRole('button', { name: 'Add one manually' }).click()
  await page.getByLabel('Exercise name').fill('Custom push-up')
  await page.getByRole('group', { name: 'Activity type — pick all that fit' }).getByRole('button', { name: 'Strength', exact: true }).click()
  await page.getByRole('group', { name: 'How you record it' }).getByRole('button', { name: 'Reps', exact: true }).click()
  await page.getByRole('group', { name: 'Equipment', exact: true }).getByRole('button', { name: 'Bodyweight', exact: true }).click()
  await confirm()
  await page.getByRole('heading', { name: 'Custom push-up' }).waitFor()
  const first = page.locator('.set-row').first()
  assert.equal(await first.getByLabel('Weight in pounds').isDisabled(), true)
  await first.getByLabel('Set 1 reps', { exact: true }).fill('15')
  await first.locator('.set-done-btn').click()
  await page.locator('.set-done-btn.done').waitFor()
  await finish()
  await page.getByRole('button', { name: 'Edit Custom push-up set 1', exact: true }).click()
  const editor = page.locator('form.set-editor')
  assert.equal(await editor.getByLabel('Weight (lb)', { exact: true }).count(), 0)
  await editor.getByLabel('Reps', { exact: true }).fill('18')
  await editor.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('18 reps', { exact: true }).waitFor()
  const savedSets = await page.evaluate(async () => {
    const { db } = await import('/src/data/db.ts')
    return db.sets.toArray()
  })
  const corrected = savedSets.find(set => set.recordingFormat === 'reps')
  assert.equal(corrected.weightLb, 0)
  assert.equal(corrected.reps, 18)
  console.log('PASS reps-only exercise needs no weight and remains reps-only after editing')
  assert.deepEqual(errors, [])
} finally { await browser.close() }
