import assert from 'node:assert/strict'
import { chromium } from 'playwright-core'
import { mkdirSync } from 'node:fs'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })
page.setDefaultTimeout(6000)
const errors = []
page.on('pageerror', error => errors.push(error.message))
const api = (fn, arg) => page.evaluate(async ({ fn, arg }) => {
  const { default: api } = await import('/src/data/index.ts')
  return api[fn](...(arg ?? []))
}, { fn, arg })
const open = async () => {
  await page.locator('.tabbar .scan-key').click()
  await page.getByLabel('Or enter a QR link / barcode digits').fill('https://example.test/muscles')
  await page.getByRole('button', { name: 'Go', exact: true }).click()
  await page.locator('.machine-movement').first().waitFor()
}
const choose = name => page.locator('.machine-movement').filter({ has: page.getByText(name, { exact: true }) }).click()
const map = id => page.locator(`.muscle-map[data-exercise="${id}"]`).first()
try {
  await page.goto(process.env.BASE_URL ?? 'http://localhost:5173/')
  await page.getByText('Start Workout', { exact: false }).waitFor()
  await api('saveMachine', [{ id: 'dual-muscles', nickname: 'Dual station', exerciseId: 'ex-pec-fly', exerciseIds: ['ex-pec-fly', 'ex-rear-delt-fly'], qrUrl: 'https://example.test/muscles', favorite: true }])
  await api('startWorkout', ['rt-pull'])
  await page.reload()
  await open()
  assert.equal(await page.locator('.machine-movement.current b').textContent(), 'Rear Delt Fly')
  assert.match(await page.locator('.machine-routine-hint').textContent(), /Next here in Pull/)
  assert.equal(await map('ex-rear-delt-fly').locator('[data-region="rearDelts"][data-level="primary"]').count(), 1)
  assert.equal(await map('ex-rear-delt-fly').locator('[data-region="chest"][data-level="primary"]').count(), 0)
  await choose('Pec Fly')
  assert.equal(await map('ex-pec-fly').locator('[data-region="chest"][data-level="primary"]').count(), 1)
  assert.equal((await api('getMachine', ['dual-muscles'])).lastExerciseId, undefined)
  assert.equal((await api('listSets', [(await api('getActiveWorkout')).id])).length, 0)
  console.log('PASS routine-aware choice; chest/rear-shoulder highlights; previews do not write sets or remembered choice')

  await page.getByRole('button', { name: 'Log Pec Fly sets', exact: false }).click()
  assert.equal((await api('getMachine', ['dual-muscles'])).lastExerciseId, 'ex-pec-fly')
  await page.getByLabel('Set 1 weight in pounds').fill('40')
  await page.getByLabel('Set 1 reps', { exact: true }).fill('10')
  await page.getByRole('button', { name: 'Log set 1', exact: true }).click()
  await page.locator('.saved-set').waitFor()
  const workout = await api('getActiveWorkout')
  let sets = await api('listSets', [workout.id])
  assert.equal(sets.length, 1)
  assert.equal(sets[0].exerciseId, 'ex-pec-fly')
  assert.equal(sets[0].machineId, 'dual-muscles')
  await open()
  assert.equal(await page.locator('.machine-movement.current b').textContent(), 'Rear Delt Fly')
  await page.getByRole('button', { name: 'Log Rear Delt Fly sets', exact: false }).click()
  await page.getByLabel('Set 1 weight in pounds').fill('20')
  await page.getByLabel('Set 1 reps', { exact: true }).fill('12')
  await page.getByRole('button', { name: 'Log set 1', exact: true }).click()
  await page.locator('.saved-set').waitFor()
  sets = await api('listSets', [workout.id])
  assert.deepEqual(sets.map(set => set.exerciseId).sort(), ['ex-pec-fly', 'ex-rear-delt-fly'])
  assert(sets.every(set => set.machineId === 'dual-muscles'))
  await api('finishWorkout', [workout.id])
  await page.reload()
  await open()
  assert.equal(await page.locator('.machine-movement.current b').textContent(), 'Rear Delt Fly')
  await choose('Pec Fly')
  await page.reload()
  await open()
  assert.equal(await page.locator('.machine-movement.current b').textContent(), 'Rear Delt Fly')
  console.log('PASS both movements log separately to one station; routine takes priority; last used survives reload; previews preserve it')

  await page.evaluate(async () => {
    const { default: api } = await import('/src/data/index.ts')
    await Promise.all([api.patchMachine('dual-muscles', { seatSetting: '4' }), api.patchMachine('dual-muscles', { setupNotes: 'Change handle position between exercises' })])
  })
  let machine = await api('getMachine', ['dual-muscles'])
  assert.equal(machine.seatSetting, '4'); assert.match(machine.setupNotes, /handle/)
  for (const ex of ['ex-pec-fly', 'ex-rear-delt-fly']) await api('saveAiProgram', [{ id: `dual-muscles::${ex}`, exerciseId: ex, sets: 3, reps: 12, restSeconds: 60, effortCheck: 'Sample', progression: 'Sample', createdAt: Date.now() }])
  await page.getByRole('button', { name: 'Edit exercises', exact: true }).click()
  await page.getByTitle('Remove Rear Delt Fly', { exact: true }).click()
  await page.getByRole('button', { name: 'Save exercises', exact: true }).click()
  await map('ex-pec-fly').waitFor()
  machine = await api('getMachine', ['dual-muscles'])
  assert.deepEqual(machine.exerciseIds, ['ex-pec-fly']);assert.equal(machine.lastExerciseId, undefined)
  assert.equal((await api('listSets', [workout.id])).length, 2)
  assert(await api('getAiProgram', ['dual-muscles', 'ex-rear-delt-fly']))
  console.log('PASS partial station writes preserve other fields; removing a movement preserves history/programs and clears stale remembered choice')

  await page.locator('.tabbar .tab', { hasText: 'Train' }).click()
  await page.getByTitle('Edit routine').first().click()
  await page.getByLabel('Exercise to add to routine').selectOption('ex-hip-adductor')
  await map('ex-hip-adductor').waitFor()
  assert.equal(await map('ex-hip-adductor').locator('[data-region="adductors"][data-level="primary"]').count(), 2)
  await page.locator('.routine-item .muscle-preview summary').first().click()
  mkdirSync('e2e/qol-audit/muscles', { recursive: true })
  for (const width of [320, 375, 390, 430, 1280]) {
    await page.setViewportSize({ width, height: 844 })
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    const overflowing = await page.locator('.muscle-map:visible').evaluateAll(maps => maps.filter(map => map.scrollWidth > map.clientWidth + 1).length)
    assert.equal(overflowing, 0, `map overflow at ${width}`)
    await page.screenshot({ path: `e2e/qol-audit/muscles/routine-${width}.png` })
  }
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  const profileAudit = await page.evaluate(async () => {
    const { exerciseMuscles, muscleLabels } = await import('/src/lib/exercise-muscles.ts')
    const { default: api } = await import('/src/data/index.ts')
    const exercises = await api.listExercises()
    return { missing: exercises.filter(ex => exerciseMuscles(ex).general).map(ex => ex.id), badRegions: exercises.flatMap(ex => { const p = exerciseMuscles(ex);return [...p.primary, ...p.secondary].filter(key => !(key in muscleLabels)) }), fallback: exerciseMuscles({ id: 'custom', name: 'Custom', equipment: 'machine', muscleGroups: ['core'] }) }
  })
  assert.deepEqual(profileAudit.missing, []);assert.deepEqual(profileAudit.badRegions, [])
  assert.equal(profileAudit.fallback.general, true);assert(profileAudit.fallback.primary.includes('abs'))
  assert.deepEqual(errors, [])
  console.log('PASS routine previews; all seeded exercises mapped; honest custom fallback; 320/375/390/430/1280px layouts; no page errors')
} finally { await browser.close() }
