from pathlib import Path
import json,re,shutil
out=Path('artifacts/machine-muscle-report')
shutil.copy('app/public/fonts/anton.woff2',out/'assets/anton.woff2')
maps=json.loads((out/'muscle-demos.json').read_text())
favicon=re.search(r'<link rel="icon"[^>]+>',Path('artifacts/mobile-ux-report/index.html').read_text()).group()
parts=['''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Explain(gz): Machine exercises & muscle map</title>''',favicon,'''<link rel="stylesheet" href="style.css"><script src="report.js" defer></script></head><body><header><a href="#">GYM ZERO <span>/ EXERCISE GUIDE</span></a><a href="https://pages.subir.dev/1d5c81f3-8ead-4a9d-aab0-de50bf12284a/">Earlier UX report ↗</a></header><main><section class="hero"><div><p class="eyebrow">IMPLEMENTED / MOBILE FIRST</p><h1>ONE MACHINE.<br>MORE WAYS<br>TO TRAIN<span>.</span></h1><p class="lead">Save the station once. Choose its exercise. See the muscles. Then log your sets.</p><p>A dual-use machine is one physical station with several movements. The updated app helps you compare those movements and see which one fits your current routine.</p><a class="cta" href="#workflow">How to use it ↓</a><a class="plain" href="#screens">Before & after ↓</a></div><div class="demo"><p class="eyebrow">TRY THE MUSCLE MAP</p><div class="choices" role="group" aria-label="Preview an exercise"><button data-choice="pec" aria-pressed="true">Pec Fly</button><button data-choice="rear" aria-pressed="false">Rear Delt Fly</button></div>''']
for key,markup in maps.items():
 markup=markup.replace('_r_',f'{key}_r_')
 parts.append(f'<div class="demo-pane" data-pane="{key}" {"hidden" if key!="pec" else ""}>{markup}</div>')
parts.append('''<p class="fine">Interactive illustration using the app’s actual SVG component. It does not log workouts or call AI.</p></div></section>
<nav aria-label="Report sections"><a href="#workflow">Workflow</a><a href="#choose">Which exercise?</a><a href="#saved">What gets saved</a><a href="#screens">Screenshots</a><a href="#changes">Changes & checks</a><a href="#qa">Q&A</a></nav>
<section id="workflow"><p class="eyebrow">01 / USING A MULTI-USE STATION</p><h2>Choose a movement,<br>not another machine.</h2><div class="steps"><article><span>1</span><h3>Save the station once</h3><p>Scan its QR code. For a new station, give it a name and add every supported exercise. Catalog matches or AI can suggest the list; you can correct it. Preview muscles before saving.</p></article><article><span>2</span><h3>Compare the choices</h3><p>Tap an exercise card. Its movement description and front/back muscle map update immediately. Lime means main muscles; blue means assisting muscles. Text labels carry the same information.</p></article><article><span>3</span><h3>Open it for logging</h3><p>Tap “Log [exercise] sets.” This remembers your choice and opens the set logger. Your active workout continues; a new one starts only when needed. Previewing alone does not log a set.</p></article><article><span>4</span><h3>Train another movement</h3><p>Return to the station, select its other exercise, and log those sets too. You keep one station record while the two exercises retain their own sets and AI programs.</p></article></div><div class="note"><b>Already saved it with only one exercise?</b><p>Open the station → Edit exercises → Add another exercise → Save exercises. Add only movements that your physical station supports. Removing one from this list does not erase its previous sets or saved program.</p></div></section>
<section id="choose"><p class="eyebrow">02 / DECIDING WHAT TO DO</p><h2>Use your routine.<br>Compare the muscles.</h2><p class="intro">If a current routine has an unfinished exercise on this station, the app marks it “Next here” and shows the number of completed sets. This is a routine-based cue, not an AI guess about what your body needs.</p><div class="table-scroll"><table><thead><tr><th>Station example</th><th>Exercise</th><th>Main target / difference</th></tr></thead><tbody><tr><td rowspan="2">Dual fly</td><td>Pec Fly</td><td>Chest · bring arms together in front.</td></tr><tr><td>Rear Delt Fly</td><td>Rear shoulders · open arms apart; upper back assists.</td></tr><tr><td rowspan="2">Leg extension / curl</td><td>Leg Extension</td><td>Front thighs (quads) · straighten knees.</td></tr><tr><td>Leg Curl</td><td>Back thighs (hamstrings) · bend knees.</td></tr><tr><td rowspan="2">Inner / outer thigh</td><td>Hip Adductor</td><td>Inner thighs · bring legs together. Newly added to the catalog.</td></tr><tr><td>Hip Abductor</td><td>Outer hips and glutes · open legs apart.</td></tr></tbody></table></div><p class="fine">These are examples of combination stations. A station must physically support both movements; selecting an exercise in the app does not make it compatible.</p><p>Without a routine, use the target groups to choose the area you intend to train. You do not need to perform every exercise a machine supports. For the dual fly example: choose Pec Fly for chest work, or Rear Delt Fly for rear-shoulder work.</p></section>
<section id="saved"><p class="eyebrow">03 / WHAT GETS SAVED</p><h2>One station.<br>Separate exercise records.</h2><div class="save-diagram"><div class="station">YOUR DUAL FLY STATION</div><div class="branches"><div><b>Pec Fly</b><p>Its own sets<br>Its own starter program</p></div><div><b>Rear Delt Fly</b><p>Its own sets<br>Its own starter program</p></div></div></div><div class="table-scroll"><table><thead><tr><th>Information</th><th>How it is stored</th></tr></thead><tbody><tr><td>Machine</td><td>One station record, with a list of supported exercise IDs.</td></tr><tr><td>Each logged set</td><td>Workout, exercise, machine, weight, reps, set number, and time.</td></tr><tr><td>AI starter program</td><td>One saved program per <code>machineId::exerciseId</code>. Changing the rear-delt program does not replace the pec-fly program.</td></tr><tr><td>Remembered choice</td><td><code>lastExerciseId</code> is saved when you open an exercise for logging. It survives reloads. Tapping cards just to preview does not change it.</td></tr><tr><td>Seat and setup notes</td><td>Currently shared for the whole station. They are not separate per movement.</td></tr><tr><td>Previous performance and strength baseline</td><td>Grouped by exercise across stations. Sets retain a machine ID, but previous-performance suggestions are not filtered to that machine.</td></tr><tr><td>Storage</td><td>Saved on the device in IndexedDB, using the existing account sync when configured. Preview diagrams are local app content.</td></tr></tbody></table></div><div class="note"><b>What opens when you return?</b><p>An exercise explicitly opened from the workout takes priority. Otherwise: the next unfinished routine movement on this station → last used exercise → the station’s default exercise. You can always choose another supported movement.</p></div></section>
<section id="screens"><p class="eyebrow">04 / ACTUAL APP SCREENS</p><h2>The visual changes.</h2><p class="intro">Before images were captured immediately before this feature, after the earlier QoL pass. After images show this implementation. Same 390 × 844 viewport and sample station/routine, with relevant sections scrolled into view. Tap an image to enlarge it.</p>''')
for slug,title,desc in [('pec','Choosing Pec Fly','Before: small muscle-group text below a large instruction area. After: movement cards come first, with a visible selection, current-routine context, and a chest-focused human diagram.'),('rear','Choosing Rear Delt Fly','The diagram switches to rear shoulders and assisting upper back. The routine cue shows that Rear Delt Fly belongs in the sample Pull session, while Pec Fly remains an optional alternative.'),('workout','While logging sets','A collapsible “Muscles & movement” section makes the same diagram available during the workout. It starts closed so the set inputs stay easy to reach.')]:
 parts.append(f'<article class="comparison"><div><h3>{title}</h3><p>{desc}</p></div><div class="pair">')
 for v in ['before','after']:
  parts.append(f'<figure><figcaption>{v.upper()}</figcaption><button class="shot" data-src="assets/{v}-{slug}.png" data-label="{title} — {v}"><img src="assets/{v}-{slug}.png" alt="{title}, {v}" width="390" height="844" loading="lazy"></button></figure>')
 parts.append('</div></article>')
parts.append('''<h3>Closer views of the new maps</h3><div class="pair closeups">''')
for slug,label in [('pec','Chest / Pec Fly'),('rear','Rear shoulders / Rear Delt Fly')]:parts.append(f'<figure><figcaption>{label}</figcaption><button class="shot" data-src="assets/after-{slug}-map.png" data-label="{label}"><img src="assets/after-{slug}-map.png" alt="Updated {label} muscle diagram and logging action" width="390" height="844" loading="lazy"></button></figure>')
parts.append('''</div></section>
<section id="changes"><p class="eyebrow">05 / IMPLEMENTATION & VERIFICATION</p><h2>What changed behind it.</h2><ul class="change-list"><li><b>24 offline exercise profiles.</b> Movement descriptions and main/assisting muscle groups cover the built-in catalog. The original SVG model has front/back views and 18 muscle regions. Custom/unknown exercises use a general map from their saved groups without inventing a main/assisting ranking.</li><li><b>Hip Adductor added.</b> Inner-thigh work can now be saved alongside Hip Abductor on a compatible station. Existing catalogs receive the missing exercise while existing edited records are preserved.</li><li><b>Maps throughout the flow.</b> Preview while creating/editing a machine, choosing a saved station’s exercise, adding/editing routine exercises, and logging a workout.</li><li><b>Better choice context.</b> Cards describe the motion, indicate selection accessibly, and show routine progress. The instruction video moves below exercise selection into an expandable section.</li><li><b>Remembering without accidental logging.</b> Opening the logger persists the last exercise; preview taps stay read-only. Removing a movement clears an invalid remembered choice while keeping history and programs.</li><li><b>Safer station writes.</b> Partial updates merge inside a transaction, so updating notes does not overwrite a separately saved choice or seat value.</li><li><b>AI follows the selected movement.</b> A newly saved multi-use machine does not automatically generate a program for its first exercise. Program feedback is cleared when switching exercises so a correction for one movement does not leak into another.</li><li><b>Clear storage explanation.</b> The station includes an expandable explanation of what is shared and what is separate. Previous sets are labeled by exercise rather than implying they came only from that station.</li></ul>
<div class="checks"><b>VERIFIED</b><p>Production build · full 44-step walkthrough · machine-AI suite · new machine-muscles suite · QoL suite · mobile audit.</p><p>New checks cover routine choice, highlighted regions, preview-versus-save behavior, reload persistence, both exercise/machine identities, partial writes, removal without losing history, all catalog profiles, custom fallback, and 320 / 375 / 390 / 430 / 1280px layouts.</p></div><p class="fine">Browser automation uses sample data and mocked AI. No real phone, live AI model, camera permissions, or multi-device sync verification was performed for this feature. The build still reports dependency annotations and a roughly 549KB JavaScript chunk warning. No additional rendering dependency was added.</p>
<details class="files"><summary>Files changed for this feature</summary><ul><li><code>app/src/components/MuscleMap.tsx</code> — new SVG model, legend, reusable preview.</li><li><code>app/src/lib/exercise-muscles.ts</code> — new exercise guidance and region mappings.</li><li><code>app/src/screens/Machine.tsx</code> — selection, routine context, previews, remembering, storage explanation.</li><li><code>app/src/screens/Workout.tsx</code> — collapsible muscle view and accessible station link.</li><li><code>app/src/screens/RoutineEdit.tsx</code> — existing/new exercise previews.</li><li><code>app/src/styles.css</code> — phone layouts, selection cards, diagram styles.</li><li><code>app/src/types.ts</code> — remembered choice and partial machine API.</li><li><code>app/src/data/index.ts</code> — transactional partial machine updates.</li><li><code>app/src/data/seed.ts</code> — Hip Adductor for new/existing catalogs.</li><li><code>app/e2e/machine-muscles.mjs</code> — new regression suite.</li><li><code>app/e2e/flow.mjs</code> — updated choice and expandable-instructions expectations.</li><li><code>app/package.json</code> — new test command.</li><li><code>README.md</code> — workflow, persistence, diagram scope, test instructions.</li></ul><p class="fine">The capture script and this site are additional report artifacts under <code>artifacts/</code>.</p></details></section>
<section id="qa"><p class="eyebrow">06 / Q&A</p><h2>Practical details.</h2><details><summary>Should I do every exercise on a machine?</summary><p>No. Follow the current routine’s marked movement or choose the target area you intend to train. Other supported movements are available; they are not an instruction to add extra work.</p><p class="fine">Why this matters: a list of capabilities should not look like a required checklist.</p></details><details><summary>Is this a personalized muscle-activation simulation?</summary><p>No. It is a schematic muscle-group guide for general exercise understanding. Color distinguishes main and assisting groups, not effort percentages, measured activation, or recovery. Setup and technique can change emphasis.</p><p class="fine">Why this matters: the diagram helps compare exercises without overstating what the app knows about your body.</p></details><details><summary>Does it work when AI is unavailable?</summary><p>Yes. The profiles and SVG diagram ship with the app. AI is optional for identifying an unknown station or generating/refining its starter program.</p><p class="fine">Why this matters: choosing an exercise should not depend on a network request.</p></details><details><summary>Can the same movement have different notes on different stations?</summary><p>Each station has its own notes. Within one station, those notes are still shared by its exercises. AI programs are separate for each machine/exercise pair.</p><p class="fine">Why this matters: this separates current station-level setup behavior from program storage.</p></details><details><summary>Is the updated application live?</summary><p>The implementation is in the local working tree and has passed the checks above. This public page is the explanation and screenshots; the application itself was not deployed.</p><p class="fine">Why this matters: publishing a walkthrough is separate from releasing the app.</p></details></section>
<footer><b>GYM ZERO</b><p>Machine selection & muscle visualization · September 2026</p><a href="#">Back to the model ↑</a></footer></main><dialog id="zoom"><div><span id="zoom-label"></span><button id="close">Close ×</button></div><img id="zoom-img" alt=""></dialog></body></html>''')
(out/'index.html').write_text(''.join(parts))
css=Path('app/src/styles.css').read_text().split('/* Exercise choice and offline muscle-group diagrams. */')[1]
(out/'muscle-map.css').write_text(css)
print('Feature report built with 8 screenshots and actual interactive SVG maps.')
