from pathlib import Path
from html import escape as e
import shutil,json
out=Path('artifacts/mobile-ux-report'); assets=out/'assets'
for p in assets.glob('debug-*.png'): p.unlink()
font=Path('app/public/fonts/anton.woff2')
if font.exists(): shutil.copy(font,assets/'anton.woff2')
# Text describes implemented behavior; screenshot pairs come from actual browser runs.
scenes=[
('home','Navigation','A familiar home, clearer navigation','The home layout already provided workout and food entry points. The center scan icon had no visible label, and several cards behaved like buttons without being actual buttons.','The Scan label makes the middle destination explicit. Home actions use button semantics, and starting training resumes an existing workout when one is active.','Keep the familiar visual identity while making destinations easier to recognize and operate.'),
('fuel','Food','Put food logging at the top','Logging controls sat below the nutrition and hydration content. Separate full-width carbs and fat rows pushed the next action farther down a small screen.','Log food and Scan barcode are now directly below the Fuel heading. Carbs and fat sit in a compact context row, with calorie-target context.','Get to the main task sooner, with less scrolling before the first useful tap.'),
('food-entry','Food','A composer that explains the options','The photo action was an icon, connection readiness was absent here, and manual fields followed the AI action without a clear transition.','The composer shows AI readiness, a labeled Photo action, and an “Or enter by hand” divider. It appears before recent/saved rails and scrolls into view. Closing it keeps the draft in the current app session.','Understand which entry method you are using and leave the screen without losing an unfinished draft.'),
('ai-working','AI','Know when AI is actually working','A disabled “Analyzing…” button was the main indication of progress. There was no elapsed time or visible way to stop the request.','A shared progress panel shows the task, a spinner, elapsed seconds, review expectations, and Stop request. After 15 seconds, the message acknowledges the longer wait. Automatic retries have their own visible status.','You can distinguish waiting from failure and stop a request without abandoning your draft.'),
('ai-question','AI','Questions and corrections follow one pattern','When AI asked a question, feedback lived inside that question with a compact arrow action. Other review states exposed feedback differently.','Suggested answers remain available. A separate, consistently visible “Correct or clarify” field and Update estimate action work alongside the question. The review states that the food has not been logged.','Answer a question or explain a correction without learning a different interaction for each response.'),
('ai-review','AI','Feedback is always available','A review without a follow-up question hid corrections behind “Did it get something wrong? Tell it.” It was easy to miss the feedback path.','The correction box is always visible. You can edit the numbers, remove items, then send a correction; the follow-up uses the current edited review. Add is the explicit step that logs the food.','Correct the estimate in context and know exactly when it becomes a saved entry.'),
('ai-error','AI','Give failed requests a next step','The authorization error appeared as a line of text beneath the AI button. Recovery relied on interpreting the error and trying the original action again.','Errors appear in a dedicated panel with Try again. Connection status, Settings access when unavailable, and actionable error text support recovery. The composer stays present.','A failed request leaves an understandable route forward. In this example the readiness probe succeeds but the request is rejected; “ready” describes that probe, not a guarantee of request success.'),
('food-saved','Food','Confirm the save and offer undo','Tapping a quick meal added a row, but there was no explicit saved notice or undo action. Editing depended on discovering that the food name was tappable.','A top notice names the logged food and offers Undo. Food rows display Edit. The notice has its own reserved space, away from bottom navigation and workout controls.','Know the tap registered, recover from an accidental add, and discover editing without guessing.'),
('food-edit','Food','Make small food edits easier to enter','The editor used compact fields and controls. Its edit affordance was hidden until the row was opened.','Larger controls, clearer labels, aligned fields, validation, and a save guard support the existing editor. Save confirmation acknowledges the edit.','Change portions and nutrition with fewer precision taps. This edit path confirms saves; it is not an undo history for every edit.'),
('empty-workout','Training','An empty workout now has a next step','Starting an empty workout led to “Pick an exercise” without a picker on that screen. The queue was empty.','An Add an exercise selector and short instruction appear in the session. Exercises can also be added to an existing workout.','Start training from an empty session without needing to discover the scanner as an indirect way forward.'),
('workout','Training','Make set logging more dependable','Set inputs and check buttons were small, blank slots did not consistently use routine targets, and a saved row changed without a separate confirmation.','Larger labeled controls, numeric validation, and a save notice make logging clearer. Exercise-specific drafts and selection survive tab changes. Routine target reps fill missing values; target completion points toward the next exercise.','Log with less thumb precision, avoid duplicate sets, and return to the exercise and values you were using.'),
('rest-away','Training','Rest keeps running while you log food','Leaving the workout stopped the rest timer, so switching to Fuel removed it.','The rest strip remains visible across tabs. Add 30 seconds or Skip from the strip. Completion shows a notice and requests vibration on devices that support it.','Check nutrition or another screen between sets without silently losing your timer.'),
('routine-editor','Training','Give routine rows room to breathe','Exercise names, tiny reorder arrows, sets, and reps shared a tight row. Controls competed for horizontal space.','Each exercise name sits above labeled Sets and Reps controls. Reorder and remove controls have larger targets. Sets are bounded to 1–10 and reps to 1–50, with save feedback and duplicate-tap protection.','Read the exercise first and adjust its targets more confidently. The roomier rows intentionally make long routines taller.'),
('scanner','Navigation','An unavailable camera looks unavailable','An animated scanning line continued in an empty camera frame. The unavailable message offered manual entry but no retry control.','Starting, blocked, and unavailable states are explicit. The scan animation appears only with an active camera. Retry camera and contextual instructions sit above manual entry. The input has an associated label and supports Go on the keyboard.','See whether the camera is starting or needs intervention, then retry or type a code. Both images show an environment without an available camera.'),
('machine-unknown','AI','Give identification some context','An unknown machine offered Ask AI without a nearby connection indicator or a place to give identifying details.','AI readiness and an optional machine-details field appear before Ask AI. The same correction/retry path remains available when identification fails.','Tell AI what you can see on the machine instead of relying entirely on an uninformative QR link.'),
('machine-guide','AI','A guide can be corrected','The cached guide showed setup advice and a program action, but lacked a clear, inline way to revise that advice.','A “Correct or clarify the guide” field and Update AI guide action sit below the advice. Copy distinguishes guide corrections from the separate Edit exercises action.','Explain a mistaken machine identification or setup detail without confusing it with editing your saved exercise list.'),
('program','AI','Adjust a program without losing the old one','A saved starter program offered Recalculate, but no visible text feedback explaining what should change.','An “Adjust your program” field and Update program action accept feedback. The existing program stays visible during the request. The request includes the previous program and current baseline/history.','Say “the starting weight feels too heavy” and review a replacement when it arrives. Separate programs per machine and exercise already existed; this pass protects them from stale results and selection races.'),
('settings','AI','Separate saving from connection testing','AI configuration used a connected indicator and Test & Save, but provided less explicit save feedback. Concurrent form saves could reuse an old settings snapshot.','The save result says whether settings were saved and the connection was reachable. Fields are disabled while testing. Converted forms patch only their own settings inside a transaction.','Know whether the values were stored even if a connection check fails, and avoid unrelated settings being overwritten by another save.'),
('weight-saved','Other','Acknowledge body and weight saves','The weight display changed after logging, but a separate success message was absent. Similar body forms did not consistently guard against repeated saves.','Weight logging shows “Weight saved” and guards invalid or repeated submissions. Body goals, composition readings, and tape sessions use shared saving/error feedback and busy guards.','Get a clear response after entering a measurement. This screenshot demonstrates weight confirmation; body and tape changes are also documented below.'),
('summary','Other','Save notes without changing workout duration','The note button already showed “Saved,” but saving notes reused finishing logic that could restamp the workout end time. A blank note could not reliably clear an existing one.','Saving shows a shared confirmation. The original finish time is preserved and empty text can clear the note. The summary has loading and missing-workout states with a way back to Stats.','Update your notes later while keeping the workout duration accurate.')]
sections=[
('AI requests: one understandable lifecycle',[
('Connection states','A shared connection component distinguishes not set up, checking, ready, and unavailable. Unavailable connections offer retry and Settings. A configured endpoint can still be tried when the availability probe fails; manual entry remains available.'),
('Connection normalization','Endpoint handling accepts an address without a scheme and normalizes a trailing /v1. This reduces configuration mistakes when copying the proxy address.'),
('Progress and recovery','Food estimates, machine guides, and starter programs use the shared task hook. It exposes elapsed time, a longer-wait message, automatic retry status, cancellation, and recoverable request errors. Authorization, timeout, network, and malformed-response errors are handled explicitly.'),
('Cancellation is functional','Stop aborts the active request. Leaving a screen aborts its task, and cancelled late responses are ignored. A synchronous task guard prevents a second request before React has updated the busy state. Cancellation does not claim to stop work already executing on a remote server.'),
('Response validation','Program and machine-guide response shapes are checked before use. This protects the UI from malformed model output; it does not establish the factual quality of model advice.')]),
('Food review, saving, and draft continuity',[
('Consistent feedback','The review always exposes a correction field, whether AI asks a follow-up question or returns items immediately. Update estimate is labeled in words. Copy explains that review is not logging; Add saves the result.'),
('Corrections use what you see','Follow-ups include current manual edits, removed items, and merges, rather than reverting to the original estimate. Photo entry shows a preview and supports corrections. Conflicting review controls are disabled while a request runs.'),
('Draft scope','Food text/photo/review state and workout input drafts survive tab navigation in memory during the current app session. They are not durable across page reloads or closing the app. Closing the food composer explicitly says it keeps the draft.'),
('Saved feedback and undo','Manual, recent, saved-meal, and AI food additions provide a saved notice and undo. Food and drink removals can be undone, including linked records. Barcode adds and food edits confirm saving but do not all provide undo. Notices are a current-action recovery mechanism, not a permanent multi-step undo history.'),
('Input confidence','Food fields have accessible labels and validation. Guarded saves prevent rapid duplicate submissions. The visible Edit affordance makes existing rows discoverable as editable content.')]),
('Hydration and nutrition stay in step',[
('Atomic additions','A caloric drink creates its hydration record and food record in one database transaction. Both records succeed together, so a partial save cannot leave one ledger without the other.'),
('Linked removal and restoration','Deleting either side of a linked drink/food pair removes the pair. Undo restores both records. Bulk AI food saving also commits the group together.'),
('Live updates','Dexie subscriptions refresh affected food and hydration views when records change. Container lists rely on the subscription instead of combining it with a manual append, which could briefly display the new container twice.'),
('Feedback around the tap','Drink notices name the amount and mention included calories where relevant. Adding a container confirms the save. Drink and container writes use busy guards.')]),
('Training without lost context',[
('Entry and exercise selection','An empty session has an exercise picker. Existing sessions can add exercises. Starting through Home or routine actions resumes an active workout instead of creating a competing session.'),
('Set entry','Draft values are keyed by exercise and the selected exercise is remembered during tab navigation. Missing target reps can use the routine target. Weight and reps receive strict validation; set writes are protected against double taps.'),
('Set identity and next steps','Set numbering does not reuse a deleted set number. A save notice names the set and values. Removal has explanatory feedback, and completed targets expose the next exercise. Finish/discard actions are protected against accidental or overlapping actions.'),
('Rest','The rest timer belongs to the app, not just the workout screen. It survives tab changes, offers +30 seconds and Skip, and announces completion. Content has extra bottom space while the strip is present. Vibration depends on browser/device support; this is not a background push-notification feature.'),
('Routine editing','Exercise names and target fields use separate rows. Larger reorder controls, labeled sets/reps, bounds, and save feedback improve editing. Routine start and edit use separate button targets.')]),
('Machine guidance and asynchronous correctness',[
('Identification and guide feedback','Unknown machines accept optional details before asking AI. A failed identification still has a correction/retry route. Saved guides can be revised through an inline text field; guidance copy explains where to edit the saved exercise list.'),
('Program refinement','Feedback is sent with the previous program. Generating reads the current strength baseline and workout history, rather than relying only on older screen state. The saved program remains available while a replacement is being requested.'),
('Keep the right result on screen','An old database read cannot overwrite a newly generated program. Program display is tied to the selected exercise so switching between exercises does not show a mismatched program.'),
('Existing capability preserved','The baseline already supported multiple exercises on one machine and separate machine/exercise programs. This pass improves their feedback and race protection; it does not claim to introduce that underlying capability.')]),
('Navigation, camera, and touch behavior',[
('Browser navigation','In-app screen changes integrate with the History API, so native browser Back returns through visited screens. Repeated navigation to the current screen is ignored. Page titles reflect the current screen and the content uses a main landmark.'),
('Buttons and selection','Home, routine, scan-result, and video actions use actual buttons. Navigation reports its active destination with ARIA state, segmented controls report their selected value, and Scan has a visible text label.'),
('Camera recovery','The scanner exposes starting, blocked, and unavailable states with appropriate instructions and Retry camera. It stops the misleading scan animation when the camera is unavailable. Lookup results are not clickable while loading; manual entry has a busy state and keyboard Go handling.'),
('Touch and motion','Shared controls have larger touch targets and visible focus/pressed states. The audited forms use a 16px input font floor to reduce unwanted mobile zoom. Fields align more consistently. Reduced-motion preferences are respected and the screen-entry wipe animation is removed.'),
('Instruction links','Instruction URLs are checked for an allowed scheme before opening. This makes external instruction actions more predictable.')]),
('Settings, measurements, and loading states',[
('Partial settings updates','The new patchSettings API merges the fields being changed inside a transaction. Converted targets, AI/training-profile, and body-goal forms avoid overwriting unrelated settings with an older full snapshot.'),
('Measurement feedback','Weight, body goals, composition readings, and tape sessions use save confirmation and busy guards. Empty readings/tape submissions are disabled; weight logging guards invalid values. Existing charts remain, with shared mobile sizing improvements.'),
('Workout notes','Editing a finished workout preserves finishedAt. A blank note clears previous text. Notes have an accessible label, a guarded Save action, and shared confirmation.'),
('Loading and sync','Initial app loading has a readable status and reload recovery on failure. Missing summaries offer a way back to Stats. After synced data is applied, shared settings, the active workout, and the exercise catalogue refresh together. This is a local behavior improvement, not evidence of a complete live multi-device sync test.')]),
('Shared feedback and regression coverage',[
('Reusable action feedback','FeedbackProvider renders saved/error messages with status/alert roles. Notifications reserve top space rather than covering bottom actions. Undo can report failure and be retried. useAction applies a synchronous lock before running an asynchronous write.'),
('Tests that fail honestly','Existing walkthrough scripts now exit unsuccessfully when a step fails. The app package adds QoL and machine-AI test commands; generated QoL audit images are ignored by Git.'),
('Documentation','README describes the AI feedback/correction flow, session-scoped drafts, rest behavior, and how to run the new checks. The application pass changed 30 existing files and added 6 files. This report and its capture script are additional documentation artifacts.')])]
files={
'App shell & shared UI':[
('app/src/App.tsx','Browser Back, rest across tabs, initial-load recovery, sync refresh, page title, main landmark.'),
('app/src/main.tsx','Install shared feedback provider.'),
('app/src/components/Feedback.tsx','NEW · Notice UI, undo handling, and guarded asynchronous actions.'),
('app/src/components/AiStatus.tsx','NEW · Shared AI readiness, progress, and error/retry UI.'),
('app/src/hooks/useAiTask.ts','NEW · Cancellable tasks, elapsed time, retry status, late-response protection.'),
('app/src/components/TabBar.tsx','Visible Scan label and accessible active navigation.'),
('app/src/components/Seg.tsx','Accessible pressed state for segmented selections.'),
('app/src/components/VideoPlayer.tsx','Button semantics for video interaction.'),
('app/src/styles.css','Mobile controls, feedback space, AI states, routine rows, camera status, focus/motion styling.')],
'Data & AI':[
('app/src/lib/ai.ts','Endpoint/status handling, retries/cancellation, feedback context, response validation.'),
('app/src/data/food-actions.ts','NEW · Transactional food/drink actions and linked undo.'),
('app/src/data/index.ts','Atomic partial settings updates and finished-workout note correctness.'),
('app/src/types.ts','Declare patchSettings on the data API.')],
'Screens':[
('app/src/screens/Food.tsx','Entry layout, draft continuity, consistent AI review/corrections, live data, saves and undo.'),
('app/src/components/HydrationCard.tsx','Live hydration, transactional logging, linked removal/undo, container save feedback.'),
('app/src/screens/Workout.tsx','Exercise picker, per-exercise drafts, validated guarded set logging, completion actions.'),
('app/src/screens/Machine.tsx','Guide/program feedback, current generation context, stale-result protection.'),
('app/src/screens/RoutineEdit.tsx','Larger labeled routine fields, bounds and guarded saving.'),
('app/src/screens/Routines.tsx','Separate routine start/edit buttons and active-workout behavior.'),
('app/src/screens/Home.tsx','Real button actions and existing-workout resume behavior.'),
('app/src/screens/Scan.tsx','Camera states/retry, manual-entry labels, lookup guards, result buttons.'),
('app/src/screens/Settings.tsx','Test/save status, busy fields, partial writes, targets/profile feedback.'),
('app/src/screens/Body.tsx','Body-goal partial writes, measurement/tape save guards and feedback.'),
('app/src/screens/History.tsx','Validated, guarded weight logging and confirmation.'),
('app/src/screens/Summary.tsx','Loading/missing states, guarded notes and clearing, save notice.')],
'Tests & documentation':[
('app/e2e/quality-of-life.mjs','NEW · AI failure/cancel/retry, edited context, writes/undo, drafts/rest, Back, concurrency, layout checks.'),
('app/e2e/machine-ai.mjs','NEW · Separate machine programs, feedback, cancellation, failed identification recovery.'),
('app/e2e/flow.mjs','Update general walkthrough for current UI; fail the process when steps fail.'),
('app/e2e/food-check.mjs','Update food walkthrough assertions/selectors and failure exit.'),
('app/e2e/food-week-check.mjs','Update weekly nutrition walkthrough and failure exit.'),
('app/e2e/hydration-check.mjs','Update hydration walkthrough and failure exit.'),
('app/e2e/mobile-audit.mjs','Update mobile checks and failure exit.'),
('app/e2e/scan-camera.mjs','Make fake-camera test failures produce a failing exit.'),
('app/package.json','Add e2e:qol and e2e:machine-ai scripts.'),
('app/.gitignore','Ignore generated QoL audit screenshots.'),
('README.md','Document behavior, draft limits, and regression commands.')]
}
faq=[
('Are these real before-and-after screenshots?','Yes. Before screenshots were reproduced from baseline commit 00f64ed in a separate temporary checkout; after screenshots come from the current working tree. Both use isolated browser contexts, matching sample data, and a 390 × 844 mobile viewport. They are actual application renders, not painted mockups. Relevant sections were scrolled into view, so scroll offsets can differ.','Provenance matters because a polished concept image would not demonstrate implemented behavior.'),
('Did you test a real AI model?','No. Automated flows and report captures use deterministic simulated proxy responses, including delayed, rejected, malformed, and successful responses. This verifies UI and control flow, not model accuracy or reachability of your actual proxy.','A reliable progress UI and a reliable model answer are different things to verify.'),
('Will unfinished entries survive closing the app?','Food and workout drafts survive tab changes within the current app session. Reloading or closing the app resets those in-memory drafts. Saved records remain in the existing local database.','This defines exactly when it is safe to expect an unfinished entry to still be there.'),
('Does every action have Undo?','No. Manual, recent, saved-meal, and AI food additions, drink additions, and linked food/drink removals support it. Barcode saves and food edits confirm success but do not all offer undo. Only the currently displayed notice exposes its undo action.','Recovery should be described precisely instead of promising a complete history of reversible actions.'),
('Did the visual identity change?','The dark surfaces, lime actions, condensed headings, and overall navigation remain. The pass prioritizes clear actions, state feedback, spacing, labels, and touch targets. Larger fields make some screens longer.','The aim was to make the familiar application easier to use on a phone, with a deliberate space-versus-density tradeoff.'),
('Is the application deployed?','No application deployment was performed for this pass. The implementation is in the local working tree. This Subir page publishes only the walkthrough and sample screenshots.','A public report link should not be confused with a release of the working application.'),
('What still needs real-device verification?','Use a physical phone with the real proxy to verify camera permission prompts, Safari/keyboard behavior, vibration, and AI reachability/answer quality. Background app suspension and live multi-device sync were not established by this browser pass. The production build also retains dependency annotation notices and a roughly 534KB JavaScript chunk warning.','These checks depend on hardware, browser policies, actual networking, or deployment behavior beyond simulated browser tests.')]
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#151617"><title>Explain(gz): Mobile UX improvements</title><meta name="description" content="Gym Zero mobile UX walkthrough: 20 actual before-and-after comparisons, implemented changes, and test evidence."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 76 76'%3E%3Crect width='76' height='76' rx='16' fill='%230c0c0d'/%3E%3Cpath fill='%23e5ff53' d='M20,17L43.25,17L56,29.75L56,59L20,59ZM24,21L24,55L52,55L52,34L39,34L39,21ZM43,22.25L43,30L50.75,30ZM30,48L34,48L34,39.5L37,42.5L37,37.75L32,32.75L27,38.25L27,42.5L30,39.5ZM38,49L38,53L26,53L26,49Z'/%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><script src="report.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="mast"><a class="brand" href="#">GYM ZERO<span> / FIELD NOTES</span></a><span class="edition">MOBILE UX · SEPT 2026</span></header><main id="main">
<section class="hero wrap"><div><p class="eyebrow">IMPLEMENTED · EXPLAINED · PHOTOGRAPHED</p><h1>LESS GUESSING.<br>MORE DOING<span>.</span></h1><p class="lead">A mobile-first quality-of-life pass for Gym Zero. Clearer taps, visible AI progress, consistent corrections, and fewer ways to lose your place.</p><div class="hero-actions"><a class="primary" href="#screens">See the before & after ↗</a><a class="secondary" href="#details">Read every change ↓</a></div><p class="hero-note">Implementation is in the local working tree. This page is the report, not a deployed version of the app.</p></div><div class="hero-art"><span class="overline">ACTUAL APP · AFTER</span><img src="assets/after-ai-review.png" width="390" height="844" alt="Updated food AI review with an always-visible correction field"><span class="art-note">YOU CAN ALWAYS<br>TELL IT WHAT TO CHANGE.</span></div></section>
<div class="metrics wrap"><div><strong>20</strong><span>matched screen comparisons</span></div><div><strong>36</strong><span>app, test & documentation files</span></div><div><strong>8</strong><span>browser suites passed</span></div><div><strong>5</strong><span>viewport widths checked</span></div></div>
<nav class="contents wrap" aria-label="Report sections"><a href="#overview">What changed</a><a href="#screens">Screenshots</a><a href="#demo">Try the flow</a><a href="#details">Full change log</a><a href="#validation">Validation</a><a href="#files">Files</a><a href="#questions">Q&A</a></nav>
<section class="wrap section" id="overview"><p class="eyebrow">01 / THE OUTCOME</p><h2>The app tells you<br>what is happening.</h2><p class="intro">The biggest changes answer the questions that interrupt a phone user: Did my tap work? Is AI waiting or broken? Where do I correct it? Did that save? Can I leave this screen?</p><div class="outcomes"><article><span>01</span><h3>Visible state</h3><p>AI readiness, elapsed time, retry, stop, errors, and save notices make the next step understandable.</p></article><article><span>02</span><h3>Consistent feedback</h3><p>Food reviews, machine guides, and programs expose written feedback where you review the result.</p></article><article><span>03</span><h3>Better continuity</h3><p>Session drafts survive tab changes, rest keeps running, native Back works, and repeated taps are guarded.</p></article></div><div class="provenance"><b>How to read the evidence</b><p>All 40 comparison images are real browser screenshots at 390 × 844. “Before” is a reproduced baseline from commit <code>00f64ed</code>; “After” is the updated working tree. Both use sample data and simulated AI responses. They show UI behavior, not real model quality. Screens are scrolled to the relevant content.</p></div></section>
<section class="wrap section" id="screens"><p class="eyebrow">02 / THE VISUAL WALKTHROUGH</p><h2>Before. After.<br>What it means for you.</h2><p class="intro">Twenty moments in the app, paired with the problem, implementation, and practical benefit. Tap any image to inspect it at full size.</p><div class="gallery-controls"><label>Show an area<select id="area"><option value="All">All 20 comparisons</option><option>AI</option><option>Food</option><option>Training</option><option>Navigation</option><option>Other</option></select></label><div><span class="control-label">Compare</span><div class="seg" role="group" aria-label="Screenshot version"><button data-mode="both" aria-pressed="true">Both</button><button data-mode="before" aria-pressed="false">Before</button><button data-mode="after" aria-pressed="false">After</button></div></div><span id="count" role="status">20 comparisons</span></div><div id="gallery" data-mode="both">'''
parts=[head]
for i,(slug,cat,title,before,after,benefit) in enumerate(scenes,1):
 parts.append(f'<article class="comparison" data-area="{cat}" id="view-{slug}"><div class="comparison-text"><p class="eyebrow">{i:02d} / {cat.upper()}</p><h3>{e(title)}</h3><dl><dt>Before</dt><dd>{e(before)}</dd><dt>Changed</dt><dd>{e(after)}</dd></dl><p class="benefit"><span>FOR YOU</span>{e(benefit)}</p><a class="permalink" href="#view-{slug}" aria-label="Link to comparison: {e(title)}">Link to this comparison ↗</a></div><div class="pair">')
 for v in ['before','after']:
  parts.append(f'<figure class="{v}"><figcaption><b>{v.upper()}</b><span>{"BASELINE 00f64ed" if v=="before" else "CURRENT APP"}</span></figcaption><button class="shot" data-image="assets/{v}-{slug}.png" data-caption="{e(title)} — {v.capitalize()}" aria-label="Enlarge {v} screenshot: {e(title)}"><img src="assets/{v}-{slug}.png" width="390" height="844" loading="lazy" alt="{e(title)}: {v} application screen"></button></figure>')
 parts.append('</div></article>')
parts.append('''</div></section><section class="wrap section" id="demo"><p class="eyebrow">03 / AN INTERACTIVE EXPLANATION</p><div class="demo-grid"><div><h2>The new AI rhythm.</h2><p class="intro">Try the states below. This is an illustrative mock UI in Gym Zero’s visual style. It does not call AI or save food.</p><ol class="flow"><li><b>Ready</b><span>Connection state is visible before the request.</span></li><li><b>Working</b><span>The app names the task and gives you a stop action.</span></li><li><b>Review & correct</b><span>The correction field is always there.</span></li><li><b>Save</b><span>A separate action confirms the food is logged.</span></li></ol><div class="demo-controls"><button id="demo-error">Show an error</button><button id="demo-reset">Reset demo</button></div></div><div class="mock"><div class="mock-top">GYM ZERO <span>ILLUSTRATIVE DEMO</span></div><div id="demo-body" aria-live="polite"></div></div></div></section>
<section class="wrap section" id="details"><p class="eyebrow">04 / THE COMPLETE CHANGE LOG</p><h2>Visible improvements.<br>Underlying fixes.</h2><p class="intro">The screenshots show the interface. These notes cover the state, persistence, data integrity, and recovery work behind it.</p><div class="details-list">''')
for i,(title,items) in enumerate(sections,1):
 parts.append(f'<article class="detail-block"><div class="detail-heading"><span>{i:02d}</span><h3>{e(title)}</h3></div><div>')
 for title,body in items:parts.append(f'<p><b>{e(title)}.</b> {e(body)}</p>')
 parts.append('</div></article>')
parts.append('''</div><div class="data-flow"><p class="eyebrow">ONE TAP / TWO LINKED RECORDS</p><div><span>Log a caloric drink</span><i>→</i><span>One transaction<br><small>hydration + nutrition</small></span><i>→</i><span>Both views update</span></div><p>Remove either linked entry → both are removed. Undo → both are restored.</p></div></section>
<section class="wrap section" id="validation"><p class="eyebrow">05 / VERIFICATION</p><h2>Tested flows.<br>Clearly stated limits.</h2><p class="intro">The application pass completed the production build and eight browser suites. The later report capture run reproduced all 20 scenarios in each version.</p><div class="table-wrap"><table><thead><tr><th>Check</th><th>Result</th><th>What it covers</th></tr></thead><tbody>
<tr><td><code>npm run build</code></td><td><span class="pass">PASS</span></td><td>TypeScript and Vite production build.</td></tr>
<tr><td><code>e2e</code></td><td><span class="pass">PASS · 44 steps</span></td><td>General app walkthrough.</td></tr>
<tr><td><code>e2e:food</code></td><td><span class="pass">PASS · 11 steps</span></td><td>Food entry and logging flows.</td></tr>
<tr><td><code>e2e:hydration</code></td><td><span class="pass">PASS · 10 steps</span></td><td>Hydration and linked calorie flows.</td></tr>
<tr><td><code>e2e:food-week</code></td><td><span class="pass">PASS · 8 steps</span></td><td>Weekly nutrition views.</td></tr>
<tr><td><code>e2e:scan</code></td><td><span class="pass">PASS · 3 steps</span></td><td>Fake-camera barcode detection, including WASM fallback.</td></tr>
<tr><td><code>e2e:mobile</code></td><td><span class="pass">PASS</span></td><td>Mobile layout and control audit.</td></tr>
<tr><td><code>e2e:qol</code></td><td><span class="pass">PASS</span></td><td>AI cancel/late response/retry/errors, edited feedback context, duplicate taps, linked undo, drafts, rest, Back, concurrent writes, note duration, viewport checks.</td></tr>
<tr><td><code>e2e:machine-ai</code></td><td><span class="pass">PASS</span></td><td>Machine/exercise program separation, refinement, cancellation, failed identification recovery.</td></tr>
</tbody></table></div><div class="validation-grid"><article><h3>Layout evidence</h3><p>Checked 320, 375, 390, 430, and 1280px widths. The final audited mobile screens had no horizontal overflow, no undersized targets under the audit’s rules, and no inputs below the 16px floor.</p><p class="muted">These findings apply to the inspected screens and states; they are not a claim of a full accessibility certification.</p></article><article><h3>Still outside this pass</h3><p>No live proxy/model evaluation, physical-phone or real Safari verification, real camera-permission test, or production application deployment. Vibration and camera behavior depend on device support.</p><p class="muted">Build succeeds with existing dependency annotation notices and a roughly 534KB JavaScript chunk warning.</p></article></div></section>
<section class="wrap section" id="files"><p class="eyebrow">06 / THE FILE INVENTORY</p><h2>Where the work lives.</h2><p class="intro">30 existing files modified; 6 new application/test files. Expand each group for its responsibilities. Paths are repository-relative.</p>''')
for group,rows in files.items():
 parts.append(f'<details class="file-group"><summary>{e(group)}<span>{len(rows)} files</span></summary><div class="file-list">')
 for path,desc in rows:parts.append(f'<div><code>{e(path)}</code><p>{e(desc)}</p></div>')
 parts.append('</div></details>')
parts.append('''<p class="muted report-artifacts">Report artifacts are separate: <code>artifacts/mobile-ux-report/</code> contains this site; <code>artifacts/capture-mobile-report.mjs</code> reproduces the comparisons; <code>artifacts/capture-manifest.json</code> records their provenance. No application source or credentials are embedded in this site.</p></section><section class="wrap section" id="questions"><p class="eyebrow">07 / QUESTIONS & ANSWERS</p><h2>What to know<br>before using the changes.</h2>''')
for q,a,why in faq:parts.append(f'<details class="faq"><summary>{e(q)}</summary><p>{e(a)}</p><p class="why"><b>Why this question matters:</b> {e(why)}</p></details>')
parts.append('''</section><footer class="wrap"><a class="brand" href="#">GYM ZERO</a><p>Mobile UX improvement report · September 12, 2026<br>Baseline 00f64ed → current working tree · Sample data in every screenshot.</p><a href="#screens">Back to comparisons ↑</a></footer></main><dialog id="lightbox"><div class="lightbox-bar"><p id="lightbox-caption"></p><button id="close-lightbox" aria-label="Close enlarged screenshot">Close ×</button></div><img id="lightbox-image" alt=""><p class="lightbox-hint">Actual 390 × 844 capture · scroll to inspect · Escape to close</p></dialog></body></html>''')
(out/'index.html').write_text(''.join(parts))
shutil.copy('artifacts/capture-manifest.json',out/'capture-manifest.json')
print(f'Built report: {len(scenes)} comparisons, {sum(len(x) for x in files.values())} files, {sum(len(x) for _,x in sections)} detailed changes')
